Repository manytask/manytask, pull requests merged in 2022-09, with the labels that each got.

#22 fix: `/report` with no score cause error
  README.md
  manytask/api.py
  manytask/main.py
Labels: type: fix

#23 fix: None columns in new student add
  manytask/gdoc.py
  requirements.txt
Labels: type: fix

#24 chore: lib version updates
  requirements.test.txt
  requirements.txt
Labels: type: chore

#25 feat: update gitlab repos layout
  .course.example.yml
  .env.example
  manytask/config.py
  manytask/glab.py
  manytask/main.py
Labels: type: feature

#26 docs: update docs with new gitlab layout
  docs/production.md
  docs/system_setup.md
Labels: type: docs

#27 fix: update check if 0 users
  manytask/gdoc.py
Labels: type: fix

#15 feat: Solutions reporting
  manytask/api.py
  manytask/config.py
  manytask/course.py
  manytask/gdoc.py
  manytask/main.py
  manytask/solutions.py
  tests/test_solutions.py
Labels: type: feature, type: test

#29 fix: handle zero division in total column
  manytask/gdoc.py
Labels: type: fix

#31 feat: admin download solution on a web page
  manytask/api.py
  manytask/glab.py
  manytask/templates/layout.html
  manytask/templates/tasks.html
  manytask/web.py
Labels: type: feature

#32 fix: error in solutions aggregation
  manytask/solutions.py
  manytask/web.py
  tests/test_solutions.py
Labels: type: fix, type: test

#33 fix: fix admin members check
  manytask/glab.py
Labels: type: fix

#34 fix: copy `shared_runners_enabled` from forked project
  manytask/glab.py
Labels: type: fix
