Repository manytask/manytask, pull requests merged in 2024-12, with the labels that each got.

#190 refactor: separate and make abstract gdoc api
  manytask/abstract.py
  manytask/api.py
  manytask/course.py
  manytask/gdoc.py
  manytask/main.py
  manytask/web.py
Labels: refactor

#193 feat: add db models for DatabaseApi
  manytask/models.py
  requirements.txt
  tests/test_models.py
Labels: feature

#194 feat: create a database and make it possible to use it instead of gsheet
  manytask/abstract.py
  manytask/api.py
  manytask/course.py
  manytask/gdoc.py
  manytask/main.py
  manytask/models.py
  manytask/web.py
  requirements.txt
  tests/test_models.py
Labels: feature

#202 refactor: add database supporting
  .env.example
  manytask/main.py
Labels: refactor

#201 feat: create database api class
  .env.example
  .gitignore
  manytask/database.py
  manytask/main.py
  tests/.deadlines.test.yml
  tests/.deadlines.test2.yml
  tests/test_db_api.py
Labels: feature

#200 refactor: edit models
  .env.example
  .gitignore
  manytask/database.py
  manytask/main.py
  manytask/models.py
  tests/.deadlines.test.yml
  tests/.deadlines.test2.yml
  tests/test_db_api.py
  tests/test_models.py
Labels: refactor

#218 chore: update docker-compose configuration for production environment
  docker-compose.production.yml
Labels: chore

#221 feat: add auto creation of tables in database
  .env.example
  manytask/database.py
  manytask/main.py
  tests/test_db_api.py
Labels: feature
