Repository manytask/manytask, pull requests merged in 2025-01, with the labels that each got.

#227 feat: add web db viewer
  .env.example
  manytask/api.py
  manytask/auth.py
  manytask/database_utils.py
  manytask/main.py
  manytask/templates/database.html
  manytask/templates/layout.html
  manytask/web.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_database_utils.py
  tests/test_main.py
  tests/test_web.py
Labels: feature

#226 ci: update docker compose for local development, add YC suport to dockerfile, add Makefile
  Dockerfile
  Makefile
  docker-compose.development.yml
  init-db.sh
Labels: ci

#228 docs: Deadline checklist
  README.md
  docs/deadline_schedule.md
Labels: documentation

#243 refactor(tests): reorganize import statements and clean up test files
  tests/test_api.py
  tests/test_auth.py
  tests/test_course.py
  tests/test_database_utils.py
  tests/test_db_api.py
  tests/test_main.py
  tests/test_web.py
Labels: test, refactor

#242 feat: enhance development workflow with pre-commit hooks and Makefile
  .pre-commit-config.yaml
  Makefile
  README.md
  scripts/check_staged.sh
Labels: feature

#244 refactor: @requires_ready and @requires_auth in web requests
  manytask/web.py
  requirements.txt
Labels: refactor

#240 test: Full coverage models.py
  tests/test_models.py
Labels: test

#231 docs: Add notes on manytask development strategy
  docs/img/course_as_a_code.png
  docs/img/stage0.png
  docs/img/stage1-2.png
  docs/img/stage3.png
  docs/img/stage4-5.png
  docs/strategy.md
Labels: documentation

#247 feat: add synchronization course_admin from gitlab to manytask
  manytask/abstract.py
  manytask/database.py
  manytask/gdoc.py
  manytask/models.py
  manytask/web.py
  tests/test_abstract.py
  tests/test_db_api.py
  tests/test_gdoc.py
  tests/test_models.py
  tests/test_web.py
Labels: feature

#246 refactor: Improve switching between database and Google sheets
  .env.example
  manytask/abstract.py
  manytask/config.py
  manytask/database.py
  manytask/gdoc.py
  manytask/local_config.py
  manytask/main.py
  manytask/templates/layout.html
  manytask/web.py
  tests/test_db_api.py
  tests/test_main.py
  tests/test_web.py
Labels: refactor

#260 feat: Cover the interaction with Gitlab by tests #215
  tests/test_glab.py
Labels: feature, test

#250 feat: enhance import sorting in staged files with isort integration in check_staged.sh
  scripts/check_staged.sh
Labels: feature

#266 feat: add endpoint and modal to update student scores in the database
  manytask/api.py
  manytask/database.py
  manytask/templates/database.html
  manytask/web.py
  tests/test_abstract.py
  tests/test_api.py
  tests/test_db_api.py
  tests/test_gdoc.py
  tests/test_models.py
  tests/test_web.py
Labels: feature

#268 fix: improve web page rendering and navigation. always show links
  manytask/templates/layout.html
  manytask/web.py
Labels: fix

#269 feat: add CSV export button to database table
  manytask/templates/database.html
Labels: feature

#271 feat: secret check
  manytask/auth.py
  manytask/web.py
  tests/test_web.py
Labels: feature

#278 refactor: migrate from isort to ruff for import sorting and formatting
  .github/workflows/test.yml
  .pre-commit-config.yaml
  Makefile
  manytask/abstract.py
  manytask/api.py
  manytask/auth.py
  manytask/config.py
  manytask/course.py
  manytask/database.py
  manytask/database_utils.py
  manytask/gdoc.py
  manytask/glab.py
  manytask/main.py
  manytask/models.py
  manytask/solutions.py
  manytask/web.py
  pyproject.toml
  scripts/check_staged.sh
  tests/test_abstract.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_course.py
  tests/test_database_utils.py
  tests/test_db_api.py
  tests/test_gdoc.py
  tests/test_glab.py
  tests/test_main.py
  tests/test_models.py
  tests/test_solutions.py
  tests/test_web.py
Labels: refactor
