Repository manytask/manytask, pull requests merged in 2025-02, with the labels that each got.

#280 feat: add option to collapse task groups in db viewer
  manytask/database_utils.py
  manytask/templates/database.html
  tests/test_database_utils.py
Labels: feature

#282 fix: use UTC timezone for datetime in solution export
  manytask/api.py
Labels: fix

#284 feat: add task group update mechanism in config handling
  manytask/abstract.py
  manytask/api.py
  manytask/database.py
  manytask/gdoc.py
  tests/test_api.py
  tests/test_database.py
Labels: feature

#291 ci: set up review policy
  .github/workflows/team-pr-reviewers.yml
Labels: ci

#292 fix: improve Tabulator table column and cell styling
  manytask/templates/database.html
Labels: fix

#270 refactor: rename tester token
  .env.example
  README.md
  docs/production.md
  manytask/api.py
  manytask/local_config.py
  tests/test_api.py
  tests/test_db_api.py
  tests/test_main.py
  tests/test_web.py
Labels: test, refactor

#298 feat: check user on course instead check fork
  manytask/abstract.py
  manytask/auth.py
  manytask/database.py
  manytask/gdoc.py
  tests/test_auth.py
  tests/test_db_api.py
  tests/test_web.py
Labels: feature

#297 fix: add naming convention for database
  manytask/models.py
Labels: fix

#299 feat: Add Colima Docker support and improve PostgreSQL container testing
  Makefile
  tests/conftest.py
  tests/test_database.py
  tests/test_db_api.py
  tests/test_main.py
Labels: feature, test

#267 feat: course token stored in db
  manytask/api.py
  manytask/course.py
  manytask/database.py
  manytask/main.py
  manytask/migrations/versions/bcca2f4efa74_add_token.py
  manytask/models.py
  tests/test_api.py
  tests/test_db_api.py
  tests/test_models.py
Labels: feature

#300 feat: login in one handler
  manytask/auth.py
  manytask/database.py
  manytask/web.py
  tests/conftest.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_db_api.py
  tests/test_web.py
Labels: feature

#307 chore: add cyclomatic complexity limit and fix lint
  manytask/api.py
  manytask/course.py
  manytask/database.py
  manytask/gdoc.py
  manytask/glab.py
  manytask/main.py
  manytask/web.py
  pyproject.toml
  tests/test_api.py
  tests/test_auth.py
  tests/test_database_utils.py
  tests/test_db_api.py
  tests/test_gdoc.py
  tests/test_glab.py
  tests/test_models.py
  tests/test_web.py
Labels: chore, fix

#310 fix: Fix version file
  VERSION
Labels: fix

#255 refactor: migrate to Poetry for dependency management and update Make…
  .github/workflows/test.yml
  Dockerfile
  Makefile
  README.md
  docs/dev.md
  docs/system_setup.md
  poetry.lock
  pyproject.toml
  requirements.test.txt
  requirements.txt
Labels: refactor
