Repository manytask/manytask, pull requests merged in 2025-09, with the labels that each got.

#588 chore: Add Oleg to the list of developers
  README.md
Labels: chore

#585 feat: log more actions
  manytask/api.py
  manytask/auth.py
  manytask/database.py
  manytask/glab.py
  manytask/main.py
  manytask/utils/generic.py
  manytask/web.py
Labels: feature

#583 perf: optimization of the course page rendering
  manytask/database.py
  manytask/models.py
  manytask/templates/layout.html
  tests/test_models.py
Labels: performance

#616 refactor: optimize repo existance check
  manytask/glab.py
  tests/test_glab.py
Labels: refactor
