Repository manytask/manytask, pull requests merged in 2025-04, with the labels that each got.

#359 fix: fixed problems with starting app
  Dockerfile
Labels: fix

#355 refactor: remove Viewer API
  manytask/abstract.py
  manytask/course.py
  manytask/database.py
  manytask/main.py
  manytask/web.py
  tests/test_auth.py
  tests/test_db_api.py
  tests/test_main.py
  tests/test_web.py
Labels: refactor

#367 fix: Supress Docker build warning
  Dockerfile
Labels: fix

#366 feat: Show student names in the scores table and CSV export
  manytask/database_utils.py
  manytask/templates/database.html
  tests/test_database_utils.py
  tests/test_web.py
Labels: feature

#368 feat: Show student names in the scores table and CSV export (#366)
  manytask/database_utils.py
  manytask/templates/database.html
  tests/test_database_utils.py
  tests/test_web.py
Labels: feature

#374 fix: Catch exception when user is deleted from gitlab
  manytask/database_utils.py
Labels: fix

#354 refactor: Move ownership of gitlab repo urls to Course class
  manytask/api.py
  manytask/auth.py
  manytask/course.py
  manytask/database_utils.py
  manytask/glab.py
  manytask/main.py
  manytask/web.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_database_utils.py
  tests/test_glab.py
  tests/test_web.py
Labels: refactor

#376 refactor: Make fields added to the Course object private
  manytask/course.py
Labels: refactor

#379 fix: Disable poetry cache
  .github/workflows/test.yml
Labels: fix
