Repository manytask/manytask, pull requests merged in 2025-08, with the labels that each got.

#481 docs: how to use local db
  docs/dev.md
  docs/dev_setup.md
  docs/production.md
  docs/toc.yaml
Labels: documentation

#498 refactor: Do not set admin status when projects are created
  manytask/web.py
Labels: refactor

#527 ci: correct using 'on'
  .github/workflows/test.yml
Labels: ci

#524 fix: data leak in `test_data_api.py`
  manytask/database.py
  tests/conftest.py
  tests/test_db_api.py
Labels: fix, test, refactor

#533 feat: refresh oauth token
  manytask/abstract.py
  manytask/auth.py
  manytask/glab.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_web.py
Labels: feature, refactor

#532 docs: add docs how to get started dev
  .env.example
  docs/dev.md
Labels: documentation

#537 refactor: rename sync_stored_user
  manytask/abstract.py
  manytask/auth.py
  manytask/database.py
  manytask/web.py
  tests/test_database.py
  tests/test_db_api.py
  tests/test_web.py
Labels: refactor

#534 refactor: Create AuthApi and use it
  manytask/abstract.py
  manytask/auth.py
  manytask/glab.py
  manytask/main.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_main.py
  tests/test_web.py
Labels: refactor

#543 fix: fix for "add grade config" PR
  manytask/database.py
  manytask/migrations/versions/322d380606c2_add_rms_id_into_database.py
  manytask/migrations/versions/54669924eda0_add_models_for_grade_config.py
  tests/test_db_api.py
Labels: fix

#538 refactor: Store instance not course admin in StoredUser
  manytask/abstract.py
  manytask/database.py
  manytask/templates/admin_panel.html
  tests/test_abstract.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_database_utils.py
  tests/test_db_api.py
  tests/test_web.py
Labels: refactor

#544 docs: add docs and examples on configuring final grade
  .manytask.example.yml
  docs/grading.md
  docs/toc.yaml
Labels: documentation

#553 chore: Remove unused envvar from the .env file
  .env.example
Labels: chore

#554 docs: Update system setup docs
  docs/system_setup.md
Labels: documentation

#562 fix: fix problem with docker cache
  .github/workflows/deploy.yaml
Labels: fix

#558 fix: default names for public repo and students groups
  manytask/templates/create_course.html
Labels: fix

#563 docs: add docs about course statuses
  docs/course_statuses.md
  docs/grading.md
  docs/toc.yaml
Labels: documentation

#567 fix: revert bump appleboy/ssh-action
  .github/workflows/deploy.yaml
Labels: fix

#561 fix: round percents to decimals and computing percent without reload
  manytask/database_utils.py
  manytask/static/css/layout.css
  manytask/templates/database.html
  manytask/web.py
  tests/constants.py
  tests/test_database_utils.py
Labels: fix

#568 fix: Automatically create user on login
  manytask/auth.py
  manytask/database.py
  manytask/utils.py
  manytask/web.py
Labels: fix

#559 fix: Proper docker build target
  .github/workflows/publish.yml
Labels: fix

#572 fix: add csrf validation to signup
  manytask/templates/signup.html
  manytask/web.py
  poetry.lock
  pyproject.toml
  tests/test_web.py
Labels: fix

#573 fix: Form field annotation
  manytask/templates/create_course.html
  manytask/templates/edit_course.html
Labels: fix
