Repository manytask/manytask, pull requests merged in 2025-06, with the labels that each got.

#402 feat: Remove github reviewer assignment on PR creation
  .github/workflows/team-pr-reviewers.yml
Labels: feature

#384 feat: Show percent of the accumulated score in the table
  manytask/database_utils.py
  manytask/templates/database.html
  tests/test_database_utils.py
Labels: feature

#422 refactor: remove redundant methods split in Storage API
  manytask/abstract.py
  manytask/database.py
  manytask/main.py
  tests/test_database.py
  tests/test_db_api.py
Labels: refactor

#434 feat: add first and last name fields to StoredUser model
  manytask/abstract.py
  manytask/database.py
  manytask/migrations/versions/6a00bd023ee8_add_first_name_and_last_name_to_user.py
  manytask/models.py
  tests/test_abstract.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_database.py
  tests/test_db_api.py
  tests/test_models.py
  tests/test_web.py
Labels: feature

#425 docs: Use Diplodoc to build and deploy landing/pages
  .github/workflows/docs.yml
  .gitignore
  docs/.yfm
  docs/_assets/style/custom.css
  docs/img/ManytaskTextFull.png
  docs/img/ManytaskTextFullDark.png
  docs/img/bg.png
  docs/img/github-mark.png
  docs/img/gravity-ui/LICENSE
  docs/img/gravity-ui/README.md
  docs/img/gravity-ui/circles-5-random.svg
  docs/img/gravity-ui/code-pull-request.svg
  docs/img/gravity-ui/display-pulse.svg
  docs/img/gravity-ui/logo-gitlab.svg
  docs/img/gravity-ui/play.svg
  docs/img/gravity-ui/shapes-3.svg
  docs/img/telegram.png
  docs/index.yaml
  docs/production.md
  docs/toc.yaml
Labels: documentation

#438 fix: Fix migrations for non-nullable colums
  manytask/migrations/versions/6a00bd023ee8_add_first_name_and_last_name_to_user.py
Labels: fix

#445 refactor: Use constants more in DB API tests
  tests/constants.py
  tests/test_db_api.py
Labels: test, refactor
