Repository manytask/manytask, pull requests merged in 2025-07, with the labels that each got.

#450 feat: added validation, as well as additional information
  manytask/main.py
  manytask/templates/create_course.html
  manytask/templates/create_project.html
  manytask/web.py
  poetry.lock
  pyproject.toml
Labels: feature

#440 feat: Do not create user when store_score(..) and get/sync_stored_user(..) are called
  manytask/abstract.py
  manytask/api.py
  manytask/auth.py
  manytask/database.py
  manytask/web.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_database.py
  tests/test_db_api.py
  tests/test_web.py
Labels: feature

#458 feat: add first and last name in score table
  manytask/database_utils.py
  manytask/templates/database.html
  tests/test_database_utils.py
Labels: feature

#461 perf: optimize calls to db when table is rendering
  manytask/abstract.py
  manytask/database.py
  manytask/database_utils.py
  manytask/templates/database.html
  tests/test_database_utils.py
  tests/test_db_api.py
  tests/test_web.py
Labels: performance

#448 feat: Do not save GitLab instance url in Users and Courses DB models
  manytask/abstract.py
  manytask/database.py
  manytask/main.py
  manytask/migrations/versions/d8b7ebab0173_do_not_save_gitlab_instance_host_for_.py
  manytask/models.py
  manytask/web.py
  tests/test_database.py
  tests/test_db_api.py
  tests/test_models.py
Labels: feature

#453 feat: Add check_is_course_admin(..) method to StorageApi and use it
  manytask/abstract.py
  manytask/api.py
  manytask/database.py
  manytask/web.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_db_api.py
  tests/test_web.py
Labels: feature

#463 fix: final score calculation with reported score
  manytask/api.py
Labels: fix

#439 feat: add course selector
  manytask/templates/layout.html
  manytask/utils.py
  manytask/web.py
  tests/test_web.py
Labels: feature

#464 refactor: Use username instead of Student when checking if the project exists
  manytask/abstract.py
  manytask/auth.py
  manytask/glab.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_glab.py
  tests/test_web.py
Labels: refactor

#465 fix: application logs are't displayed
  Dockerfile
  manytask/main.py
Labels: fix

#437 feat: add editing page course
  manytask/abstract.py
  manytask/database.py
  manytask/templates/base.html
  manytask/templates/edit_course.html
  manytask/templates/layout.html
  manytask/web.py
  tests/test_db_api.py
  tests/test_web.py
Labels: feature

#462 refactor: move html styles to css files + UI changes
  manytask/static/css/base.css
  manytask/static/css/courses.css
  manytask/static/css/database.css
  manytask/static/css/layout.css
  manytask/static/css/tasks.css
  manytask/templates/base.html
  manytask/templates/courses.html
  manytask/templates/create_project.html
  manytask/templates/database.html
  manytask/templates/layout.html
  manytask/templates/not_ready.html
  manytask/templates/signup.html
  manytask/templates/tasks.html
  manytask/web.py
  tests/test_web.py
Labels: refactor

#475 feat: add join course section to main page
  manytask/auth.py
  manytask/templates/base.html
  manytask/templates/courses.html
Labels: feature

#476 perf: optimize dockerfile
  Dockerfile
Labels: performance

#474 feat: remove gitlab admins + add admin panel + ability to change the name
  .env.example
  manytask/abstract.py
  manytask/auth.py
  manytask/database.py
  manytask/glab.py
  manytask/main.py
  manytask/migrations/versions/428bcd9f5db6_add_role_admin_to_user_model.py
  manytask/models.py
  manytask/static/css/admin_panel.css
  manytask/templates/admin_panel.html
  manytask/templates/courses.html
  manytask/templates/layout.html
  manytask/utils.py
  manytask/web.py
  tests/test_auth.py
  tests/test_db_api.py
  tests/test_glab.py
  tests/test_main.py
  tests/test_web.py
Labels: feature

#477 feat: remove unnecessary session refreshes
  manytask/database.py
Labels: feature, refactor

#487 refactor: Set OAuth in separate function
  manytask/main.py
Labels: refactor

#493 docs: Update version
  VERSION
Labels: documentation

#490 docs: Update README file
  README.md
Labels: documentation

#495 refactor: change naming and localization
  .env.example
  manytask/database.py
  manytask/main.py
  manytask/web.py
  tests/test_db_api.py
  tests/test_main.py
Labels: refactor

#496 fix: Fix github pages
  .github/workflows/docs.yml
Labels: fix

#494 feat: Store RMS ID in the database
  manytask/abstract.py
  manytask/database.py
  manytask/migrations/versions/322d380606c2_add_rms_id_into_database.py
  manytask/models.py
  manytask/web.py
  tests/constants.py
  tests/test_abstract.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_database.py
  tests/test_db_api.py
  tests/test_models.py
  tests/test_web.py
Labels: feature

#435 refactor: Create RmsUser object and use it
  manytask/abstract.py
  manytask/api.py
  manytask/auth.py
  manytask/glab.py
  manytask/utils.py
  manytask/web.py
  tests/test_api.py
  tests/test_auth.py
  tests/test_database.py
  tests/test_database_utils.py
  tests/test_glab.py
  tests/test_web.py
Labels: refactor
