Repository manytask/manytask, pull requests merged in 2025-03, with the labels that each got.

#320 feat: add deadline config synchronization to database
  manytask/database.py
  manytask/migrations/versions/037c4373e638_add_fields_from_deadline_config.py
  manytask/models.py
  tests/.deadlines.test2.yml
  tests/test_db_api.py
  tests/test_models.py
Labels: feature

#322 feat: use deadlines and tasks stored in DB instead of filesystem
  manytask/abstract.py
  manytask/api.py
  manytask/config.py
  manytask/course.py
  manytask/database.py
  manytask/database_utils.py
  manytask/gdoc.py
  manytask/migrations/versions/b4b7a8a28ac0_add_url_to_task.py
  manytask/models.py
  manytask/templates/layout.html
  manytask/templates/tasks.html
  manytask/web.py
  tests/.deadlines.test.yml
  tests/.deadlines.test2.yml
  tests/test_api.py
  tests/test_auth.py
  tests/test_database.py
  tests/test_database_utils.py
  tests/test_db_api.py
  tests/test_gdoc.py
  tests/test_models.py
  tests/test_web.py
Labels: feature

#347 feat: install poetry command
  Makefile
Labels: feature

#356 feat: Run tests on all pull request and when changes are pushed to any branch
  .github/workflows/test.yml
Labels: feature, test

#343 feat: keep the order of groups and tasks
  manytask/config.py
  manytask/database.py
  manytask/migrations/versions/c3c1bd781e0f_add_positions_to_task_and_taskgroup.py
  manytask/models.py
  tests/test_db_api.py
  tests/test_models.py
Labels: feature

#353 refactor: Remove GoogleSheet support
  .env.example
  manytask/gdoc.py
  manytask/main.py
  tests/test_gdoc.py
  tests/test_main.py
Labels: refactor
