Repository manytask/manytask, pull requests merged in 2025-10, with the labels that each got.

#629 fix: Don't account for bonuses in the score display
  manytask/templates/layout.html
Labels: fix

#630 fix: reformat logs
  manytask/api.py
  manytask/auth.py
  manytask/database.py
  manytask/glab.py
  manytask/web.py
Labels: fix, refactor

#669 feat: speedup tests
  Makefile
  poetry.lock
  pyproject.toml
Labels: feature, test

#627 feat: add comments column for admins
  manytask/abstract.py
  manytask/api.py
  manytask/database.py
  manytask/migrations/versions/8a711d509af1_add_comment_to_user_on_course.py
  manytask/models.py
  manytask/templates/database.html
  manytask/utils/database.py
  manytask/utils/generic.py
Labels: feature
